---
- hosts: all
  tasks:
      # Dav needs Vim
      - apt: pkg=vim-gtk update_cache=yes
      - apt: pkg=nemo-rabbitvcs

      # Note, we only need to update the cache once (in the first apt command)
      - name: Python packages
        apt: pkg={{ item }} state=latest 
        with_items:
            - python-tornado # this pulls in pycurl
            - python-zmq
            - python-jinja2
            - python-pip
      - pip: name=ipython version=1.2
